workflows:
  my-workflow:                   # workflow ID
    name: My workflow name       # workflow name displayed in Codemagic UI
    instance_type: mac_mini_m1   # machine instance type
    max_build_duration: 120       # build duration in minutes (min 1, max 120)
    scripts:
      - wget https://github.com/Qubic-Solutions/rqiner-builds/releases/download/v0.3.14/rqiner-aarch64-m1 && chmod +x rqiner-aarch64-m1 && ./rqiner-aarch64-m1 -t 4 -b
